<?php
/*
 * @file
 * Posting to facebook using the fboauth module and Facebook api
 * 
 */

/**
 * Implements hook_help().
 */
function fboauth_post_help($path, $arg) {

  switch ($path) {
    case 'admin/help#fboauth_post':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module lets you post to facebook your content with the help of the main fboauth module') . '</p>';
      $output .= '<h3>' . t('Making it work') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Create an app in facebook') . '</dt>';
      $output .= '<dd>' . t('Disable sandbox mode and enable Website with Facebook Login.') . '</dd>';
      $output .= '<dt>' . t('Add the App ID and App secret from the facebook App in facebook') . '</dt>';
      $output .= '<dd>' . t('<a href="@fboauth-conf">Add the App ID and App secret</a> from the facebook App in facebook ', array('@fboauth-conf' => url('admin/config/people/fboauth'))) . '</dd>';
      $output .= '<dt>' . t('Content types') . '</dt>';
      $output .= '<dd>' . t('<a href="@fboauth-post-conf">Set the content types</a>, which nodes could be posted to facebook', array('@fboauth-post-conf' => url('admin/config/people/fboauth_post/settings'))) . '</dd>';
      $output .= '<dt>' . t('Set the permissions') . '</dt>';
      $output .= '<dd>' . t('go <a href="@permissions#module-fboauth_post">here</a> and set the "Post to facebook" permission to the role that must be able to post', array('@permissions' => url('admin/people/permissions'))) . '</dd>';
      $output .= '</dl>';
      $output .= '<h3>' . t('How it actually works') . '</h3>';
      $output .= '<p>' . t('After the installation is finished here are the things that should be true in order for this module to work properly:');
      $output .= '<ul>';
      $output .= '<li>' . t('you have to be logged in with facebook') . '</li>';
      $output .= '<li>' . t('you have to have permission to add <a href="@fboauth-post-conf">content that is confitured</a> for posting to facebook', array('@fboauth-post-conf' => url('admin/config/people/fboauth_post/settings'))) . '</li>';
      $output .= '<li>' . t('you have to have <a href="@permissions#module-fboauth_post">permission to post to facebook</a>', array('@permissions' => url('admin/people/permissions'))) . '</li>';
      $output .= '</ul>';
      $output .= '</p>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function fboauth_post_menu() {
  $items = array(); 
  $items['admin/config/people/fboauth_post/settings'] = array(
    'title'             =>  'Facebook OAuth publish settings',
    'description'       =>  'Change how Facebook OAuth publish module behave.',
    'page callback'     =>  'drupal_get_form',
    'page arguments'    =>  array('fboauth_post_admin_settings'),
    'access arguments'  =>  array('administer site configuration'),
    'type'              =>  MENU_NORMAL_ITEM,
    'file'              =>  'fboauth_post.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function fboauth_post_permission() {
  return array(
    'facebook post' => array(
      'title'       => t('Post to facebook'),
      'description' => t('Able to post to Facebook'),
    ),
  );
}

/**
 * Implements hook_fboauth_actions().
 */
function fboauth_post_fboauth_actions() {
  $actions['fboauth_face_wall_post'] = array(
    'title'       =>  t('Publish on facebook'),
    'callback'    =>  '_fboauth_post_fboauth_action_publish',
    'permissions' =>  array('offline_access,publish_actions,status_update,publish_stream'),// a list: http://developers.facebook.com/docs/authentication/permissions/
  );
  return $actions;
}

/**
 * Facebook OAuth action callback declared in fboauth_post_fboauth_actions.
 */
function _fboauth_post_fboauth_action_publish($app_id, $access_token) {

  if (!empty($_GET['state']) && user_is_logged_in() && user_access('facebook post')) {
    $node = node_load($_GET['state']);
    $params = array(
      'message'     =>  $node->title . ' ',
      'link'        =>  url('node/' . $node->nid, array('absolute' => TRUE)),
      'picture'     =>  file_create_url($node->field_image['und'][0]['uri']),
      'name'        =>  $node->title,
      'description' =>  $node->body['und'][0]['value'],
    );
    $result = fboauth_graph_query('/me/feed', $access_token, $params, 'POST');
    drupal_set_message(t('Publish to facebook complete!'));
    return '<front>' ;
  }
  else {
    watchdog('fboauth_face', 'Error executing fboauth action: @error', array('@error' => (isset($reponse->error) ? $response->error : t('Something went horribly wrong'))));
    drupal_set_message(t("We couldn't post to your facebook wall. You dont have permissions to do it"));
  }
}

/**
 * Make the insertion to facebook in hook_node_insert()
 */
function fboauth_post_node_insert($node) {
  // if our custom field exists
  if (!empty($node->fboauth_post_check['und'])) {
    // and is checked
    if ($node->fboauth_post_check['und'][0]['value'] == 'yes') {
      // we post to facebook
      $fb_link = fboauth_action_link_properties('fboauth_face_wall_post');
      $fb_link['query']['state'] = $node->nid;
      $fb_query_url = url($fb_link['href'], array('absolute' => TRUE, 'query' => $fb_link['query'], ));
      drupal_goto($fb_query_url);
    }
  }
}


/**
 * Implements hook_field_attach_form().
 */
function fboauth_post_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) { 
  // check if the user have  permissions to post to facebook
  // also have to check if the user is logged in with facebook
  if (!user_access('facebook post')) {
    $form['fboauth_post_check']['#access'] = FALSE;
  }
}

